version : '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: 'firewall-nginx'
    ports:
      - "4000:80"
    # command: copy default.conf /etc/nginx/conf.d # instead of this command use bind mount
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf 
    networks:
      - nginx-fastapi
    depends_on:
      - fastapi
  fastapi: # must named 'fastapi' cause name of the service will resolve to ip of the container in nginx config
    build:
      context: app
    container_name: 'fast-api'
    env_file:
      - .env
    networks:
      - nginx-fastapi
      - fastapi-postgress
      - fastapi-redis
    depends_on:
      - postgres
      - redis
  postgres: # you must name it like that cause in .env the db_host=postgres will resolve to ip of the container
    image: postgres:16
    expose:
      - 5432
    container_name: postgres_db
    environment:
      - POSTGRES_USER=youssef
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=psql_db 
    networks:
      - fastapi-postgress
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis: # you must name it like that cause in .env the redis_host=redis will resolve to ip of the container
    image: redis:6.2-alpine
    container_name: redis
    expose:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - fastapi-redis


networks:
  nginx-fastapi:
  fastapi-postgress:
  fastapi-redis:
volumes:
  postgres_data:
  redis_data:


